name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: lein cloverage --codecov
    - name: Upload Test Report
      run: bash <(curl -s https://codecov.io/bash)
